# Generated by Django 5.2.7 on 2025-10-13 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
