# Generated by Django 5.2.7 on 2025-10-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0003_bloguser_groups_bloguser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
